### ISSUE TITLE
normal csnm gives a random color guide lmao when it hits below 40 percent

### ISSUE THREAD

**Issue by Hakiiiiiii** [Tamaou/Tera-Dungeon-Guides#1]

**Comment by Tamaou** [comment]
can you please provide me with more details? Are you referring to the In-Out mech or the temperature? As I do not recall adding any color guide into it. 
Thanks

**Comment by Tamaou** [comment]
I will be closing this issue due to:

1. There are no further replies regarding this issue
2. I am unable to pinpoint/ replicate any scenario regarding this Issue Posted

Please do open a new issue if it appears again and please provide more details such as describing what happen at which mech etc.
Thank you
